### ISSUE TITLE
[BUG] <NFTs are not updated>

### ISSUE THREAD

**Issue by Akinci-B** [pancakeswap/pancake-frontend#2731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Other

### Current Behavior

These nfts (see attach) are bought 4 days ago and are still listed. This cannot be a BSC congestion problem because other platform like nftkey & fabboard work perfectly and instantly.

### Expected Behavior

Don't list new collection until everything is OK.

### Steps To Reproduce

1. NFT collection
2. BornBadGirls

### Environment

```markdown
- Device: Macbook Pro
- OS: Monterey 12.0.1
- Browser: Chrome
- Wallet: Metamask
```

### Anything else?

![2021-11-22 01 59 02](https://user-images.githubusercontent.com/45290040/142786844-f9915ca2-9d4f-4acb-801c-523e63689a28.jpg)

**Comment by memoyil** [comment]
Currently the node sync a bit slow due to congestion. With the BSC Bruno update (30 Nov. apprx.). Node sync will get faster. If you see your transaction success in BscScan with correct Contract Address (check always website address in address bar for phishing), you can rest assured.

More Info: 

https://www.binance.org/en/blog/binance-smart-chain-bruno-upgrade-v1-1-5/

**Comment by roeerr** [comment]
![IMG_20211122_192616_450](https://user-images.githubusercontent.com/56670097/142916490-ac167bcd-599c-4b7e-90c0-f44f2a8080e3.jpg)

**Comment by Akinci-B** [comment]
So how Fabboard works and update instantly the price of nfts ?

https://fabboard.vercel.app/bornbadgirls

**Comment by Chef-Cheems** [comment]
PancakeSwap NFT Marketplace uses subgraph to track state of the marketplace. Recently they had a lot of troubles of syncing with BSC due to node problems. It will be resolved soon, BSC team is working on it. But occasionally there can be lags, unfortunately.

Fabboard also uses subgraph but also goes and fetches the data directly from contract.
While we can do that too - it creates an enormous amount of requests while browsing marketplace. Might be ok for people with good/unlimited internet, but in some countries it would break marketplace entirely. We might implement something like that as a fallback in case subgraph is continues to lag though.

It is known issue and we're communication with TheGraph and BSC teams. Closing this issue as PCS devs can't really do much except bringing it up to other BSC teams.
