### ISSUE TITLE
[Feature Request] <# Rollback of fraudulent contract votes>

### ISSUE THREAD

**Issue by Pszz** [pancakeswap/pancake-frontend#2787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem you are facing?

My case of being cheated:
https://bscscan.com/tx/0xbee7b4f3a23fb90f13e38e6e4a1e4cfcfee92e7bc618e0e76f72da453aeb129e
https://bscscan.com/tx/0xcdef31c3bf60c7301e0eda8e6ad5045bd459ff6b8b1c6275bf924acd24661083
**
Over 3,000 BNBs worth millions of dollars scammed in just 1 exchange program
**

-  Pancake currently has too many scammers and will become more and more dangerous if it cannot be effectively restricted.
- There are currently too many fraudulent contracts, can we increase the holder's vote on the current contract to roll back the tokens in the contract?

- Let's say more than 90% of the holder's votes are considered successful?

### Describe the solution you'd like
- Holders vote on rollback contracts.
- Let's say more than 90% of the holder's votes are considered successful?

### How does this feature benefit PancakeSwap users and CAKE holders?

生态环境将更加健康

**Comment by R-K-H** [comment]
What? You executed against a BEP-20 token, what was cheated here? You can read the contract https://bscscan.com/address/0xb7b580140dd33d2de5e01da65bce1225202c0ce2#code and it's a honeypot as viewed https://honeypot.is/?address=0xb7b580140dD33d2De5e01dA65BcE1225202C0ce2

This is a decentralized exchange, there is no ability to prevent interaction between contracts, only the user's best judgement when doing so.

**Comment by Pszz** [comment]
Blockchain is the consensus mechanism, and all I want is to find ways to add disincentives to fraud.
For example, the voting mechanism I mentioned.

**Comment by R-K-H** [comment]
So would you propose that every potential token which would be published to the blockchain go up for review by the entire BSC community before you should be allowed to interact with it? There is a clear warning box which comes up which you have to click to approve which states that anyone can list any token on BSC so be warned.

I'm just pointing out the issue with trying to approve any and all contracts just because one person has an interest in it and how daunting a task that would be. I think using an external service to say this contract has been flagged with a high likelyhood of scam could be good, but again would you have just clicked the approve button anyways?

**Comment by Pszz** [comment]
的确，这将是非常麻烦的。
因此，目前没有好的办法来恢复损失的资产。

**Comment by R-K-H** [comment]
But it's not lost, you took an action, it's the result of your action. If anything education and proper research needs to be instilled in this industry. However, the barriers for entry are low and it's lessons like these which cause people to do better next time around. Hopefully those links help in the future and it's part of your due diligence when investing or interacting with tokens.

**Comment by Chef-Cheems** [comment]
Closing as its PCS is a DeX and by definition anybody can list any token. Users should do their own research.
Proposed voting mechanism is not something PCS can do, its requires entire BSC community and BSC team to do rollbacks or whatever.
