### ISSUE TITLE
NFT API Information need

### ISSUE THREAD

**Issue by r0b0roach** [pancakeswap/pancake-frontend#3415]
Hi,
I'm wondering if your Nft api is open source? Is it possible to see codes? If it is not, could you please give me some information about how it works? 

- Where collection images stored? Is it inside centralized server?
- When Nfts for one collection are fetching, does api fetchs them directly from contract or a centralized server(indexed before)?

Thanks,

**Comment by blackluv** [comment]
Centralized servers, that's why they use sentry

**Comment by chef-jojo** [comment]
> Hi, I'm wondering if your Nft api is open source? Is it possible to see codes? If it is not, could you please give me some information about how it works?
> 
> * Where collection images stored? Is it inside centralized server?
> * When Nfts for one collection are fetching, does api fetchs them directly from contract or a centralized server(indexed before)?
> 
> Thanks,

1. The images you get from frontend serve behind CDN, in order to preserve stability and performance. All NFT contract should has `tokenURI` you can get the true decentralized ipfs metadata and asset from it.
2. Collection data are mixed with NFT api and subgraph. NFT api for indexed collections, and subgraph for market data

It's a common way, almost all NFT marketplace, opensea, loooksrare they have their own centralized API to help indexing and better filtering for FE use. It's for displaying and doesn't mean the NFT itself is centralized.

About the open source, I think it's totally fine, I will let other chefs to decide. After all it's just a brunch of serverless handlers connected with mongodb that stored the collections we listed in our marketplace.

**Comment by blackluv** [comment]
Okay.
How can I hit you up
