### ISSUE TITLE
[BUG] On android, the `Copy Address` button does not work. 

### ISSUE THREAD

**Issue by Chef-Chungus** [pancakeswap/pancake-frontend#648]
**Bug Description**
On Android devices, copy to clipboard button does not work. 

**Steps to Reproduce**

1. Go to PancakeSwap on an Android device
2. Click on your address
3. Click Copy Address
4. Address doesn't get copied to clipoard.
   ...

**Expected Behavior**
Upon clicking copy to clipboard, the address gets copied to your clipboard.

**Additional Context**
![image](https://user-images.githubusercontent.com/71833681/110898935-83126380-8343-11eb-9dda-ff4d3f9332ef.png)

**Comment by memoyil** [comment]
Created a pull request in uikit

https://github.com/pancakeswap/pancake-uikit/pull/220

**Comment by ArtemKolichenkov** [comment]
I tried to reproduce this issue and here are my findings:

### Android 10
`Copy Address` works properly with:
- Chrome `89.0.4389.86`
- Brave `1.21.74` (Chromium `89.0.4389.72`)
- Firefox `86.1.1` (Build #2015794883)

The only browser that does **not** copy the address is Trust Wallet's integrated dAPP browser. It does not work there because `clipboard-write`permission is `denied` by default in WebView and iFrame.

@memoyil were you able to reproduce the issue in Chrome/Firefox/Brave on your device? Did you run your solution in Trust dApp browser?

**Comment by memoyil** [comment]
Yes, I tested it there. It works properly

**Comment by ArtemKolichenkov** [comment]
Actually just checked - turns out the whole `navigator.permission` is undefined in WebView, i.e. Trust Wallet. So maybe indeed solution by @memoyil is the only way to do it for now to support copying in TrustWallet. Not gonna lie I don't like creating textareas to just copy address, but seems like there is no other way we can fix it on our end. 🙁 

I've filed a bug report to Trust Wallet (also made an example to reproduce if you're interested) - https://github.com/trustwallet/wallet-core/issues/1324
