### ISSUE TITLE
not able to run web 

### ISSUE THREAD

**Issue by ram13369** [pancakeswap/pancake-frontend#9720]
/workspaces/pancake-frontend/apps/web (develop) $ pnpm dev

> web@0.1.0 dev /workspaces/pancake-frontend/apps/web
> next dev

file:///workspaces/pancake-frontend/apps/web/next.config.mjs:4
import smartRouterPkgs from '@pancakeswap/smart-router/package.json' with { type: 'json' }
                                                                     ^^^^

SyntaxError: Unexpected token 'with'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:115:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:293:14)
    at async link (node:internal/modules/esm/module_job:70:21)

Node.js v17.6.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by chefjackson** [comment]
Hi since security support has ended for both nodejs 16 and 17, we've update the engine requirement to [">=18"](https://github.com/pancakeswap/pancake-frontend/pull/9744/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R48). Please upgrade your nodejs version and try again. Thanks

**Comment by chefjackson** [comment]
Update on this issue: the import attribute "with" support is ported back after nodejs `18.20.0`. Please upgrade the nodejs version accordingly
